### ISSUE TITLE
`postOffer` method unexpected error on server.

### ISSUE THREAD

**Issue by abouolia** [haveno-dex/haveno-ts#117]
I want to post an offer to the Alias daemon, copied and pasted almost the same code from the test file, but keep getting that error on the Alias daemon.

I don't know if there's a misconfigratuon on my daemons. Couldn't understand the error so generic.

Code:
```
   const config = {
      direction: "buy", // buy or sell xmr
      amount: BigInt("200000000000"), // amount of xmr to trade
      assetCode: "eth", // counter asset to trade
      price: undefined, // use market price if undefined
      paymentAccountId: "50d93331-1640-41eb-b90e-e0352727008f",
      priceMargin: 0.0,
      minAmount: undefined,
      buyerSecurityDeposit: 0.15,
      awaitUnlockedBalance: false,
      triggerPrice: undefined,
    };
    
    client.postOffer(
        config.direction,
        config.amount,
        config.assetCode,
        config.paymentAccountId,
        config.buyerSecurityDeposit,
        config.price,
        config.marketPriceMargin,
        config.triggerPrice,
        config.minAmount
    );
```

Error:
```
Jun-05 12:21:39.987 [grpc-default-executor-2] INFO  b.d.g.i.CallRateMeteringInterceptor: CreateOffer has been called 1 time in the last second, rate limit is 10/second 
Jun 05, 2022 12:21:39 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@6a9420c8
io.grpc.StatusRuntimeException: UNKNOWN: unexpected error on server
	at bisq.daemon.grpc.GrpcExceptionHandler.wrapException(GrpcExceptionHandler.java:99)
	at bisq.daemon.grpc.GrpcExceptionHandler.handleException(GrpcExceptionHandler.java:56)
	at bisq.daemon.grpc.GrpcOffersService.createOffer(GrpcOffersService.java:178)
	at bisq.proto.grpc.OffersGrpc$MethodHandlers.invoke(OffersGrpc.java:569)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Jun-05 12:21:39.989 [grpc-default-executor-2] INFO  b.c.offer.CreateOfferService: create and get offer with offerId=031044-795d1c24-f77d-4027-ac64-d9b300d0ebdf-162, 
currencyCode=ETH, 
direction=BUY, 
price=100000000, 
useMarketBasedPrice=true, 
marketPriceMargin=0.0, 
amount=20000000, 
minAmount=20000000, 
buyerSecurityDeposit=0.15 
Jun-05 12:21:39.991 [grpc-default-executor-2] ERROR org.bitcoinj.core.Context: Performing thread fixup: you are accessing bitcoinj via a thread that has not had any context set on it. 
Jun-05 12:21:39.992 [grpc-default-executor-2] ERROR org.bitcoinj.core.Context: This error has been corrected for, but doing this makes your app less robust. 
Jun-05 12:21:39.992 [grpc-default-executor-2] ERROR org.bitcoinj.core.Context: You should use Context.propagate() or a ContextPropagatingThreadFactory. 
Jun-05 12:21:39.992 [grpc-default-executor-2] ERROR org.bitcoinj.core.Context: Please refer to the user guide for more information about this. 
Jun-05 12:21:39.992 [grpc-default-executor-2] ERROR org.bitcoinj.core.Context: Thread name is grpc-default-executor-2. 
Jun-05 12:21:39.992 [grpc-default-executor-2] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 2 outputs totalling 0.0302 BTC and a fee of 0.00 BTC/vkB 
Jun-05 12:21:39.992 [grpc-default-executor-2] INFO  b.c.btc.TxFeeEstimationService: We cannot do the fee estimation because there are not enough funds in the wallet. This is expected if the user pays from an external wallet. In that case we use an estimated tx vsize of 175 vbytes. 
Jun-05 12:21:39.992 [grpc-default-executor-2] INFO  b.c.btc.TxFeeEstimationService: Fee estimation resulted in a tx vsize of 175 vbytes and a tx fee of 1750 Sat. 
Jun-05 12:21:39.993 [grpc-default-executor-2] ERROR b.d.grpc.GrpcOffersService:  java.lang.NullPointerException: null
	at bisq.core.offer.CreateOfferService.createAndGetOffer(CreateOfferService.java:234)
	at bisq.core.api.CoreOffersService.createAndPlaceOffer(CoreOffersService.java:239)
	at bisq.core.api.CoreApi.createAnPlaceOffer(CoreApi.java:447)
	at bisq.daemon.grpc.GrpcOffersService.createOffer(GrpcOffersService.java:151)
	at bisq.proto.grpc.OffersGrpc$MethodHandlers.invoke(OffersGrpc.java:569)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.NullPointerException: null
	at bisq.core.offer.CreateOfferService.createAndGetOffer(CreateOfferService.java:234)
	at bisq.core.api.CoreOffersService.createAndPlaceOffer(CoreOffersService.java:239)
	at bisq.core.api.CoreApi.createAnPlaceOffer(CoreApi.java:447)
	at bisq.daemon.grpc.GrpcOffersService.createOffer(GrpcOffersService.java:151)
	at bisq.proto.grpc.OffersGrpc$MethodHandlers.invoke(OffersGrpc.java:569)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by woodser** [comment]
Is the arbitrator accessible? This line corresponds to looking up the arbitrator (needs a better error message):

https://github.com/haveno-dex/haveno/blob/8a0612a245ad0c10145bd9399926aebda07dcd54/core/src/main/java/bisq/core/offer/CreateOfferService.java#L234

**Comment by abouolia** [comment]
@woodser  Yes, my arbitrator is running and registered. and still getting that error. 

```
Jun-07 23:15:55.241 [grpc-default-executor-4] ERROR org.bitcoinj.core.Context: Performing thread fixup: you are accessing bitcoinj via a thread that has not had any context set on it. 
Jun-07 23:15:55.242 [grpc-default-executor-4] ERROR org.bitcoinj.core.Context: This error has been corrected for, but doing this makes your app less robust. 
Jun-07 23:15:55.242 [grpc-default-executor-4] ERROR org.bitcoinj.core.Context: You should use Context.propagate() or a ContextPropagatingThreadFactory. 
Jun-07 23:15:55.242 [grpc-default-executor-4] ERROR org.bitcoinj.core.Context: Please refer to the user guide for more information about this. 
Jun-07 23:15:55.242 [grpc-default-executor-4] ERROR org.bitcoinj.core.Context: Thread name is grpc-default-executor-4. 
Jun-07 23:15:55.243 [grpc-default-executor-4] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 2 outputs totalling 0.00105 BTC and a fee of 0.00 BTC/vkB 
Jun-07 23:15:55.244 [grpc-default-executor-4] INFO  b.c.btc.TxFeeEstimationService: We cannot do the fee estimation because there are not enough funds in the wallet. This is expected if the user pays from an external wallet. In that case we use an estimated tx vsize of 175 vbytes. 
Jun-07 23:15:55.244 [grpc-default-executor-4] INFO  b.c.btc.TxFeeEstimationService: Fee estimation resulted in a tx vsize of 175 vbytes and a tx fee of 8750 Sat. 
Jun-07 23:15:55.247 [grpc-default-executor-4] ERROR b.d.grpc.GrpcOffersService:  java.lang.NullPointerException: null
	at bisq.core.offer.CreateOfferService.createAndGetOffer(CreateOfferService.java:234)
	at bisq.core.api.CoreOffersService.createAndPlaceOffer(CoreOffersService.java:239)
	at bisq.core.api.CoreApi.createAnPlaceOffer(CoreApi.java:447)
	at bisq.daemon.grpc.GrpcOffersService.createOffer(GrpcOffersService.java:151)
	at bisq.proto.grpc.OffersGrpc$MethodHandlers.invoke(OffersGrpc.java:569)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

java.lang.NullPointerException: null
	at bisq.core.offer.CreateOfferService.createAndGetOffer(CreateOfferService.java:234)
	at bisq.core.api.CoreOffersService.createAndPlaceOffer(CoreOffersService.java:239)
	at bisq.core.api.CoreApi.createAnPlaceOffer(CoreApi.java:447)
	at bisq.daemon.grpc.GrpcOffersService.createOffer(GrpcOffersService.java:151)
	at bisq.proto.grpc.OffersGrpc$MethodHandlers.invoke(OffersGrpc.java:569)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Jun 07, 2022 11:15:55 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3d64d0ec
io.grpc.StatusRuntimeException: UNKNOWN: unexpected error on server
	at bisq.daemon.grpc.GrpcExceptionHandler.wrapException(GrpcExceptionHandler.java:99)
	at bisq.daemon.grpc.GrpcExceptionHandler.handleException(GrpcExceptionHandler.java:56)
	at bisq.daemon.grpc.GrpcOffersService.createOffer(GrpcOffersService.java:178)
	at bisq.proto.grpc.OffersGrpc$MethodHandlers.invoke(OffersGrpc.java:569)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Jun-07 23:16:54.552 [InputHandler-localhost:4444] WARN  b.n.p2p.network.Connection: proto is null because protoInputStream.read()=-1 (EOF). That is expected if client got stopped without proper shutdown. 

```

**Comment by woodser** [comment]
haveno-ts-0.0.6 is released which should improve the stack trace.

It runs against [current master](8a0612a245ad0c10145bd9399926aebda07dcd54).

**Comment by abouolia** [comment]
Please check my code.

1. Created crypto payment account and took the getId() and put it to the payment account.

```
const payment = {
      accountName: "asdasd",
      assetCode: "ETH",
      address: "0xdBdAb835Acd6fC84cF5F9aDD3c0B5a1E25fbd99f",
}

client.createCryptoPaymentAccount(
      payment.accountName,
      payment.assetCode,
      payment.address
    );   
 ```
The crypto account has been created well without any issue./

```
const offer = {
    direction: "buy", // buy or sell xmr
    amount: BigInt("1"), // amount of xmr to trade
    assetCode: "ETH", // counter asset to trade
    paymentAccountId: "d477c9d9-ea9b-4fd4-8019-4f0581a0a13d",
    buyerSecurityDeposit: 0.15,
}
client.postOffer(
      offer.direction,
      offer.amount,
      offer.assetCode,
      offer.paymentAccountId,
      offer.buyerSecurityDeposit,
      offer.price,
      offer.marketPriceMargin,
      offer.triggerPrice,
      offer.minAmount
);
````
Keep getting the same unexpected error.

**Comment by abouolia** [comment]
Yeah, i know `createCryptoPaymentAccount` and `postOffer` is async function. i did that.

- Arbitrator daemon works and registered it as you mentioned by Account, command + r.
- My Alice, Bob and Seednode daemons even the funding-wallet daemon work without any problem or red error.
- Mined some stagenet XMR coins to alice and bob addresses.
- In terms of testing, Tried to run the test but not all test cases passed some test cases failed.

![SCR-20220607-unt](https://user-images.githubusercontent.com/2197422/172688947-7ea02659-953a-4190-9264-0837f5f6bd8b.png)

**Comment by woodser** [comment]
Can you include more logs on the test failures? That could give a clue.

**Comment by abouolia** [comment]
After I removed the `haveno` and `haveno-ts` and built it again, got that error. 

https://www.loom.com/share/a84efa444b7c4cac8e17844038e49264

**Comment by woodser** [comment]
Ensure no instances of monero-wallet-rpc are running before starting the daemons.

If that's not the problem, try deleting the recreating the arbitrator.

**Comment by woodser** [comment]
What environment is this? Installing a local network per the instructions to verify everything works should have been one the first steps if you haven't already.

**Comment by abouolia** [comment]
All the test cases passed, and the `postOffer` works for me. Thanks @woodser for your help, i'm sorry to forget to close the issue.

**Comment by woodser** [comment]
Excellent. Great to hear.
